---
################
system:
################
  structure1:
    name:
      '2OJ9-e1'
    tlc:
      '1OL'
    complex:
      dirname:
        'complex'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_complex'
    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

  structure2:
    name:
      '2OJ9-e2'
    tlc:
      '1KE'
    complex:
      dirname:
        'complex'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_complex'
    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

################
simulation:
################
  nsteps:
    '500000'
  free-energy-type:
    'binding-free-energy'
    #'solvation-free-energy'
################
solvation:
################
  steps_for_equilibration:
    1000


  

  