---
################
system:
################
  structure1:
    name:
      'CE105'
    tlc:
      'UNK'
    complex:
      dirname:
        'complex'
      psf_file_name:
        'step5_charmm2omm'
      crd_file_name:
        'step5_charmm2omm'
      rst_file_name:
        'step6.6_equilibration'
      simulation_parameter:
        'step7_production.inp'
      intermediate-filename:
        'lig_in_complex'
    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

  structure2:
    name:
      'CE110'
    tlc:
      'UNL'
    complex:
      dirname:
        'complex'
      psf_file_name:
        'step5_charmm2omm'
      crd_file_name:
        'step5_charmm2omm'
      rst_file_name:
        'step6.6_equilibration'
      simulation_parameter:
        'step7_production.inp'
      intermediate-filename:
        'lig_in_complex'

    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

################
simulation:
################
  nsteps:
    '500000'
  free-energy-type:
    'binding-free-energy'
################
solvation:
################
  steps_for_equilibration:
    1000


  

  
